services:
  grafana:
    image: grafana/grafana-oss:13.0.2
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:?}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:?}
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - o11y-grafana-data:/var/lib/grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/api/health"]
      interval: 5s
      timeout: 20s
      retries: 10

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.147.0
    restart: unless-stopped
    command:
      - '--promscrape.config=/etc/vm/scrape.yml'
      - '--storageDataPath=/storage'
      - '--retentionPeriod=30d'
    ports:
      - "127.0.0.1:8428:8428"
    volumes:
      - o11y-vm-data:/storage
      - ./configs/victoriametrics:/etc/vm:ro

  node_exporter:
    image: prom/node-exporter:v1.11.1
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.systemd'
    ports:
      - "127.0.0.1:9100:9100"
    volumes:
      - /:/host:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /run/dbus:/run/dbus:ro
      - /run/udev:/run/udev:ro

volumes:
  o11y-grafana-data:
    name: o11y-grafana-data
  o11y-vm-data:
    name: o11y-vm-data